name: Deploy ECR BASE IMAGE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
        docker:
          image: docker:20.10
          options: >-
            --privileged
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
        
    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_LOGIN }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set region ${{ secrets.AWS_REGION }}
    - name: Build and push Docker image
      env:
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }} # Replace with your ECR repository name
        ECR_REGISTRY: ${{ secrets.AWS_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY
        docker build -t ECR_REPOSITORY .
        docker tag ECR_REPOSITORY:latest $ECR_REGISTRY/ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/ECR_REPOSITORY:latest